<a href="https://colab.research.google.com/github/Nivea5678/Yeti-Analytics/blob/Sentiment_Analysis/Optimized_sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from nltk.corpus import opinion_lexicon
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, GRU

In [3]:
# loading the data
from google.colab import files
uploaded = files.upload()

Saving Yeti Analytics.xlsx to Yeti Analytics.xlsx


In [4]:
# Step 1: Load the dataset into dataframe
df = pd.read_excel('Yeti Analytics.xlsx')
df

Review  Rating
0      nice hotel expensive parking got good deal sta...       4
1      ok nothing special charge diamond member hilto...       2
2      nice rooms not 4* experience hotel monaco seat...       3
3      unique, great stay, wonderful time hotel monac...       5
4      great stay great stay, went seahawk game aweso...       5
...                                                  ...     ...
20486  best kept secret 3rd time staying charm, not 5...       5
20487  great location price view hotel great quick pl...       4
20488  ok just looks nice modern outside, desk staff ...       2
20489  hotel theft ruined vacation hotel opened sept ...       1
20490  people talking, ca n't believe excellent ratin...       2

[20491 rows x 2 columns]

In [5]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
import nltk
nltk.download('punkt')
nltk.download('wordnet')
from keras.layers import Activation, Dense
from tensorflow.keras.layers import Bidirectional



[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


In [ ]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow as tf
from imblearn.over_sampling import RandomOverSampler

# Download NLTK resources
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
 #loading the data
from google.colab import files
uploaded = files.upload()

Saving Yeti Analytics.xlsx to Yeti Analytics (1).xlsx


In [ ]:
# Step 1: Load the dataset into dataframe
df = pd.read_excel('Yeti Analytics.xlsx')
df

Review  Rating
0      nice hotel expensive parking got good deal sta...       4
1      ok nothing special charge diamond member hilto...       2
2      nice rooms not 4* experience hotel monaco seat...       3
3      unique, great stay, wonderful time hotel monac...       5
4      great stay great stay, went seahawk game aweso...       5
...                                                  ...     ...
20486  best kept secret 3rd time staying charm, not 5...       5
20487  great location price view hotel great quick pl...       4
20488  ok just looks nice modern outside, desk staff ...       2
20489  hotel theft ruined vacation hotel opened sept ...       1
20490  people talking, ca n't believe excellent ratin...       2

[20491 rows x 2 columns]

In [7]:
import tensorflow as tf
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Preprocessing the text
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    tokens = word_tokenize(text.lower())
    tokens = [lemmatizer.lemmatize(token) for token in tokens if token.isalpha()]
    tokens = [token for token in tokens if token not in stop_words]
    return ' '.join(tokens)

df['Review'] = df['Review'].apply(preprocess_text)

In [10]:
# Data Preprocessing
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer



In [11]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
import nltk
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    text = re.sub(r'[^\w\s]', '', text)  # Remove punctuation
    text = text.lower()  # Convert to lowercase
    words = text.split()
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]  # Lemmatization and stopword removal
    return ' '.join(words)

df['Cleaned_Review'] = df['Review'].apply(preprocess_text)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from imblearn.over_sampling import RandomOverSampler
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout


# Splitting into train and test sets
X_train, X_test, y_train, y_test = train_test_split(df['Cleaned_Review'], df['Rating'], test_size=0.2, random_state=42)

# Tokenization and Padding
max_sequence_length = 100
vocab_size = 10000

tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(X_train)

X_train_sequences = tokenizer.texts_to_sequences(X_train)
X_test_sequences = tokenizer.texts_to_sequences(X_test)

X_train_padded = pad_sequences(X_train_sequences, maxlen=max_sequence_length)
X_test_padded = pad_sequences(X_test_sequences, maxlen=max_sequence_length)

# Mapping class labels to start from 0
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# One-hot encoding the labels
onehot_encoder = OneHotEncoder(sparse=False)
y_train_onehot = onehot_encoder.fit_transform(y_train_encoded.reshape(-1, 1))
y_test_onehot = onehot_encoder.transform(y_test_encoded.reshape(-1, 1))

# Handling Class Imbalance
ros = RandomOverSampler(random_state=42)
X_train_padded, y_train_onehot = ros.fit_resample(X_train_padded, y_train_onehot)

# Defining the LSTM model
model = Sequential()
model.add(Embedding(vocab_size, 128, input_length=max_sequence_length))
model.add(Bidirectional(LSTM(64, return_sequences=True)))
model.add(Bidirectional(LSTM(32)))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(len(label_encoder.classes_), activation='softmax'))

# Compiling and train the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train_padded, y_train_onehot, validation_data=(X_test_padded, y_test_onehot), epochs=10, batch_size=32)

# Evaluating the model
_, accuracy = model.evaluate(X_test_padded, y_test_onehot)
print('Accuracy: %.2f%%' % (accuracy * 100))


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Epoch 1/10
1135/1135 [==============================] - 177s 152ms/step - loss: 0.9238 - accuracy: 0.6037 - val_loss: 1.1172 - val_accuracy: 0.5511
Epoch 2/10
1135/1135 [==============================] - 164s 144ms/step - loss: 0.4782 - accuracy: 0.8132 - val_loss: 1.3788 - val_accuracy: 0.4623
Epoch 3/10
1135/1135 [==============================] - 163s 144ms/step - loss: 0.3378 - accuracy: 0.8705 - val_loss: 1.5715 - val_accuracy: 0.5562
Epoch 4/10
1135/1135 [==============================] - 161s 142ms/step - loss: 0.2648 - accuracy: 0.9030 - val_loss: 1.8087 - val_accuracy: 0.5565
Epoch 5/10
1135/1135 [==============================] - 165s 146ms/step - loss: 0.2059 - accuracy: 0.9281 - val_loss: 1.9118 - val_accuracy: 0.5475
Epoch 6/10
1135/1135 [==============================] - 165s 146ms/step - loss: 0.1693 - accuracy: 0.9434 - val_loss: 2.1540 - val_accuracy: 0.5172
Epoch 7/10
1135/1135 [==============================] - 166s 147ms/step - loss: 0.1351 - accuracy: 0.9559 - val_

In [14]:
from sklearn.metrics import confusion_matrix
import numpy as np

# Get model predictions
y_pred_prob = model.predict(X_test_padded)
y_pred = np.argmax(y_pred_prob, axis=1)

# Convert the one-hot encoded labels back to original labels
y_test_labels = onehot_encoder.inverse_transform(y_test_onehot)
y_pred_labels = label_encoder.inverse_transform(y_pred)

# Build confusion matrix
cm = confusion_matrix(y_test_labels, y_pred_labels)
print("Confusion Matrix:")
print(cm)


129/129 [==============================] - 62s 37ms/step
Confusion Matrix:
[[   0  145   74   32   20   21]
 [   0   46   93   81   80   33]
 [   0   21   56  139  150   66]
 [   0    4   37  153  571  487]
 [   0    7    8   40  418 1317]
 [   0    0    0    0    0    0]]


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from imblearn.over_sampling import RandomOverSampler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from sklearn.metrics import confusion_matrix

# Splitting into train and test sets
X_train, X_test, y_train, y_test = train_test_split(df['Cleaned_Review'], df['Rating'], test_size=0.2, random_state=42)

# Tokenization and Padding
max_sequence_length = 100
vocab_size = 10000

tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(X_train)

X_train_sequences = tokenizer.texts_to_sequences(X_train)
X_test_sequences = tokenizer.texts_to_sequences(X_test)

X_train_padded = pad_sequences(X_train_sequences, maxlen=max_sequence_length)
X_test_padded = pad_sequences(X_test_sequences, maxlen=max_sequence_length)

# Mapping class labels to start from 0
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# One-hot encoding the labels
num_classes = len(label_encoder.classes_)
onehot_encoder = OneHotEncoder(sparse=False, categories='auto')
y_train_onehot = onehot_encoder.fit_transform(y_train_encoded.reshape(-1, 1))
y_test_onehot = onehot_encoder.transform(y_test_encoded.reshape(-1, 1))

# Handling Class Imbalance
ros = RandomOverSampler(random_state=42)
X_train_padded, y_train_onehot = ros.fit_resample(X_train_padded, y_train_onehot)

# Defining the LSTM model
model = Sequential()
model.add(Embedding(vocab_size, 128, input_length=max_sequence_length))
model.add(Bidirectional(LSTM(64, return_sequences=True)))
model.add(Bidirectional(LSTM(32)))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(num_classes, activation='softmax'))

# Adjusting class weights
class_weights = dict(enumerate(len(y_train_encoded) / (num_classes * np.bincount(y_train_encoded))))

# Compiling and training the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train_padded, y_train_onehot, validation_data=(X_test_padded, y_test_onehot), epochs=5, batch_size=128, class_weight=class_weights)

# Evaluating the model
_, accuracy = model.evaluate(X_test_padded, y_test_onehot)
print('Accuracy: %.2f%%' % (accuracy * 100))

# Generating and printing the updated confusion matrix
y_pred_onehot = model.predict(X_test_padded)
y_pred = np.argmax(y_pred_onehot, axis=1)
y_test = np.argmax(y_test_onehot, axis=1)
confusion_mat = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(confusion_mat)


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Epoch 1/5
284/284 [==============================] - 205s 690ms/step - loss: 1.4158 - accuracy: 0.4910 - val_loss: 1.4421 - val_accuracy: 0.3838
Epoch 2/5
284/284 [==============================] - 198s 699ms/step - loss: 0.5455 - accuracy: 0.7378 - val_loss: 1.5320 - val_accuracy: 0.4201
Epoch 3/5
284/284 [==============================] - 205s 721ms/step - loss: 0.3366 - accuracy: 0.8017 - val_loss: 1.6479 - val_accuracy: 0.4923
Epoch 4/5
216/284 [=====================>........] - ETA: 46s - loss: 0.2676 - accuracy: 0.8309